### ISSUE TITLE
Target of URI doesn't exist: 'package:flutter_prevent_screen_capture/flutter_prevent_screen_capture.dart'. (Documentation)

### ISSUE THREAD

**Issue by RoBiN-HoOd-1** [Blacktaler/flutter_prevent_screen_capture#1]

**Comment by Blacktaler** [comment]
Hi, can you please provide some details? How did this happen?

**Comment by Blacktaler** [comment]
Can you try to: type **flutter packages get** in terminal and restart the vscode?

**Comment by Blacktaler** [comment]
Closing the issue, as this is not package related
